# Generated by Django 2.2 on 2019-04-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_voter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='Question',
            new_name='question',
        ),
    ]
