# Generated by Django 2.2 on 2019-04-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190430_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='choice_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
