# Generated by Django 2.2 on 2019-05-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190511_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_part_of_event',
            field=models.BooleanField(default=False),
        ),
    ]
