# Generated by Django 2.2 on 2019-05-11 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_question_is_part_of_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voter',
            new_name='Vote',
        ),
    ]
