# Generated by Django 2.2.1 on 2019-05-17 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190517_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
