# Generated by Django 2.2.1 on 2019-05-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190519_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='event.Event'),
        ),
    ]
