# Generated by Django 2.2.1 on 2019-05-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_transaction_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mother_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_accounts', to='account.Account'),
        ),
    ]
