# Generated by Django 2.2.1 on 2019-05-30 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190528_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_transaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
