# Generated by Django 2.2.1 on 2019-06-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_description'),
        ('user', '0002_myuser_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='account',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
