# Generated by Django 2.2.1 on 2019-06-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190602_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_account',
        ),
    ]
