# Generated by Django 2.2.1 on 2019-05-16 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190515_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voteforblog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
