# Generated by Django 2.2.1 on 2019-05-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20190521_2034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteForBlog',
        ),
    ]
