# Generated by Django 2.2.1 on 2019-05-21 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamah', '0002_auto_20190521_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamah',
            name='requested_to_join',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
