# Generated by Django 2.2.1 on 2019-05-21 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jamah', '0003_auto_20190521_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamah',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='JamahMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('creator', 'CREATOR'), ('modarator', 'MODARATOR'), ('admin', 'ADMIN'), ('member', 'MEMBER')], default='member', max_length=9)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('jamah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamah.Jamah')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
