# Generated by Django 2.2.1 on 2019-05-21 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamah', '0004_auto_20190521_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamah',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jamahs', to=settings.AUTH_USER_MODEL),
        ),
    ]
