# Generated by Django 2.2.1 on 2019-05-21 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamah', '0006_auto_20190521_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamah',
            name='requested_to_join',
            field=models.ManyToManyField(blank=True, related_name='requests_of_you', to=settings.AUTH_USER_MODEL),
        ),
    ]
