# Generated by Django 2.2.1 on 2019-05-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamah', '0008_auto_20190521_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamahmember',
            name='still_to_be_excepted',
            field=models.BooleanField(default=True),
        ),
    ]
