# Generated by Django 2.2.1 on 2019-05-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamah', '0009_jamahmember_still_to_be_excepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamahmember',
            name='is_responsible',
            field=models.BooleanField(default=False),
        ),
    ]
