# Generated by Django 2.2.1 on 2019-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamah', '0010_jamahmember_is_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamah',
            name='admin_member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jamah',
            name='modarator_member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jamah',
            name='resposible_member_count',
            field=models.IntegerField(default=1),
        ),
    ]
