# Generated by Django 2.2.1 on 2019-05-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamah', '0012_auto_20190524_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamah',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AlterField(
            model_name='jamahmember',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
