# Generated by Django 2.2 on 2019-04-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_auto_20190430_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
