# Generated by Django 2.2 on 2019-05-09 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190509_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.Account'),
        ),
    ]
