# Generated by Django 2.2 on 2019-05-09 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190509_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transactionIns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.TransactionIn'),
        ),
        migrations.AlterField(
            model_name='account',
            name='transactionOuts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.TransactionOut'),
        ),
        migrations.AlterField(
            model_name='event',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
