# Generated by Django 2.2 on 2019-05-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190509_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='transactionIns',
        ),
        migrations.RemoveField(
            model_name='account',
            name='transactionOuts',
        ),
        migrations.AddField(
            model_name='transactionin',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Account'),
        ),
        migrations.AddField(
            model_name='transactionout',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Account'),
        ),
    ]
