# Generated by Django 2.2 on 2019-05-09 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20190509_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionin',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.Account'),
        ),
        migrations.AlterField(
            model_name='transactionin',
            name='comes_from',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionout',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.Account'),
        ),
        migrations.AlterField(
            model_name='transactionout',
            name='goes_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
