# Generated by Django 2.2 on 2019-05-10 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0009_auto_20190509_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='member',
        ),
        migrations.AddField(
            model_name='event',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
