# Generated by Django 2.2 on 2019-05-10 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20190510_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='member',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
