# Generated by Django 2.2 on 2019-05-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20190510_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='member',
            new_name='members',
        ),
    ]
