# Generated by Django 2.2.1 on 2019-05-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20190519_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionin',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
