# Generated by Django 2.2.1 on 2019-05-19 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_eventmember_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
