# Generated by Django 2.2.1 on 2019-05-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20190519_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmember',
            old_name='user',
            new_name='member',
        ),
    ]
