# Generated by Django 2.2.1 on 2019-05-19 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190519_2214'),
        ('event', '0018_auto_20190519_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_donation_only_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='official_blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
