# Generated by Django 2.2.1 on 2019-05-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20190521_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='cost_bearer',
            field=models.ManyToManyField(blank=True, to='event.EventMember'),
        ),
        migrations.AddField(
            model_name='cost',
            name='extracted_money',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cost',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='event.EventMember'),
        ),
        migrations.AlterField(
            model_name='event',
            name='official_blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
