# Generated by Django 2.2.1 on 2019-05-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamah', '0009_jamahmember_still_to_be_excepted'),
        ('event', '0031_auto_20190521_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='jamah',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jamah.Jamah'),
        ),
        migrations.AlterField(
            model_name='event',
            name='official_blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
