# Generated by Django 2.2.1 on 2019-05-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_auto_20190521_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='official_blog',
        ),
    ]
