# Generated by Django 2.2.1 on 2019-05-21 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_remove_event_official_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='jamah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jamah.Jamah'),
        ),
    ]
