# Generated by Django 2.2.1 on 2019-05-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_auto_20190521_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_costs', to='event.EventMember'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_costs', to='event.EventMember'),
        ),
    ]
