# Generated by Django 2.2.1 on 2019-05-22 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_auto_20190522_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='extracted_money',
            new_name='has_extracted_money',
        ),
        migrations.AddField(
            model_name='cost',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AddField(
            model_name='cost',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cost',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='transactionin',
            name='part_of_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Cost'),
        ),
    ]
