# Generated by Django 2.2.1 on 2019-05-22 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_auto_20190522_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
