# Generated by Django 2.2.1 on 2019-05-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_auto_20190522_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='needed_approve',
            field=models.IntegerField(),
        ),
    ]
