# Generated by Django 2.2.1 on 2019-05-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_auto_20190522_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='needed_approve',
            new_name='needed_approve_count',
        ),
    ]
