# Generated by Django 2.2.1 on 2019-05-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_auto_20190522_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='is_approved',
            new_name='is_objected',
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='approved_by',
            new_name='objected_by',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='needed_approve_count',
        ),
        migrations.AddField(
            model_name='eventmember',
            name='is_responsible',
            field=models.BooleanField(default=False),
        ),
    ]
