# Generated by Django 2.2.1 on 2019-05-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_auto_20190523_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
