# Generated by Django 2.2.1 on 2019-05-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0042_cost_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
