# Generated by Django 2.2.1 on 2019-05-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_auto_20190523_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
