# Generated by Django 2.2.1 on 2019-05-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0046_auto_20190523_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
