# Generated by Django 2.2.1 on 2019-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0047_auto_20190523_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='modarator_member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='resposible_member_count',
            field=models.IntegerField(default=1),
        ),
    ]
