# Generated by Django 2.2.1 on 2019-05-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0049_auto_20190524_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionout',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transactionout',
            name='goes_to',
        ),
        migrations.DeleteModel(
            name='TransactionIn',
        ),
        migrations.DeleteModel(
            name='TransactionOut',
        ),
    ]
