# Generated by Django 2.2.1 on 2019-05-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0050_auto_20190524_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
