# Generated by Django 2.2.1 on 2019-05-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('event', '0051_auto_20190524_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
