# Generated by Django 2.2.1 on 2019-05-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0052_eventmember_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
