# Generated by Django 2.2.1 on 2019-05-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0055_remove_cost_has_extracted_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='cost_bearer',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='donation_amount',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='per_head_cost',
        ),
    ]
