# Generated by Django 2.2.1 on 2019-05-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0057_event_per_head_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_finished',
            field=models.BooleanField(default=False),
        ),
    ]
