# Generated by Django 2.2.1 on 2019-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0060_auto_20190524_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='objected_by',
            field=models.ManyToManyField(blank=True, related_name='objected_costs', to='event.EventMember'),
        ),
    ]
