# Generated by Django 2.2.1 on 2019-06-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190530_1835'),
        ('event', '0063_auto_20190602_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AlterField(
            model_name='event',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
