# Generated by Django 2.2.1 on 2019-06-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0066_auto_20190602_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_for_cost_account', to='account.Account'),
        ),
    ]
