# Generated by Django 2.2.1 on 2019-06-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0067_auto_20190602_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmember',
            old_name='account',
            new_name='accountant_account',
        ),
        migrations.RenameField(
            model_name='eventmember',
            old_name='total_sent',
            new_name='total_sent_money',
        ),
    ]
