# Generated by Django 2.2.1 on 2019-06-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0070_auto_20190604_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='is_observed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cost',
            name='observed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observed_costs', to='event.EventMember'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='is_cost_observer',
            field=models.BooleanField(default=False),
        ),
    ]
