# Generated by Django 2.2.1 on 2019-06-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0072_eventmember_total_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_donation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='total_recieved_money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
