# Generated by Django 2.2.1 on 2019-06-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0073_auto_20190605_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='timestamp',
        ),
    ]
