# Generated by Django 2.2.1 on 2019-06-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0075_eventmember_is_head_accountant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='estimated_per_head_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
